import LayoutComponent from "./LayoutComponent";
import Provider from "./Provider";
import "./globals.css";
import { M_PLUS_1 } from "next/font/google";

const mplus = M_PLUS_1({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={mplus.className}>
        <Provider>
          <LayoutComponent>{children}</LayoutComponent>
        </Provider>
      </body>
    </html>
  );
}
